# ------------------------------ COMMON ------------------------------
server:
  servlet:
    context-path: /auth
  port: 8080

springfox:
  documentation:
    swagger2:
      v2:
        path: /public/api-docs
spring:
  profiles:
    active: DEV
---
# ------------------------------ DEV ------------------------------
spring:
  profiles: DEV
  jpa:
    database: H2
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    name: development

---
# ------------------------------ TEST ------------------------------
spring:
  profiles: TEST

---
# ------------------------------ PRE_PROD ------------------------------
spring:
  profiles: PRE_PROD

---
# ------------------------------ PROD ------------------------------
spring:
  profiles: PROD